# Generated by Django 2.1.7 on 2019-02-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190220_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=True, related_name='announcement', to='courses.Course', verbose_name='Curso'),
        ),
    ]
